/*****************************************************************************
* IAR Visual State Coder Generated Header File
* Generated by IAR Visual State 9.1.1.3863
* IAR Visual State Project File: <E:\work_ypl\1_WirelessSwitchboard\3sourcecode\visualSTATE\WorkspaceYPL.vsp>
* IAR Visual State Signature Generator: "81"
* Project Signature: "e89ff9e42730e866831d14f94a50bad8"
*****************************************************************************/


#ifndef SYSTEMYPL_H
#define SYSTEMYPL_H


/** @file
    System header file.
    Contains macros and declarations for a system.
*/



/* *** include directives *** */


#include "WorkspaceYPL.h"


/* *** constants *** */


/* Events */
#define VSStartEvent 0
#define button1 1
#define button2 2
#define button3 3


/* Action function declarations */

extern void BLUE_ON (void);

extern void LED_OFF (void);

extern void RED_ON (void);


#endif
