/*****************************************************************************
* IAR Visual State Coder Generated Header File
* Generated by IAR Visual State 9.1.1.3863
* IAR Visual State Project File: <E:\work_ypl\1_WirelessSwitchboard\3sourcecode\visualSTATE\WorkspaceYPL.vsp>
* IAR Visual State Signature Generator: "81"
* Project Signature: "856e2777e7f468f0c6e8f5d52a473f69"
*****************************************************************************/


#ifndef SYSTEMYPL_H
#define SYSTEMYPL_H


/** @file
    System header file.
    Contains macros and declarations for a system.
*/



/* *** include directives *** */


#include "WorkspaceYPL.h"


/* *** constants *** */


/* Events */
#define VSStartEvent 0
#define button1 1
#define button2 2
#define button3 3
#define DOOR 4
#define ON 5
#define ROTATION 6
#define STOP 7
#define WASH 8
#define E1 9
#define E2 10
#define E3 11


/* Action function declarations */

extern void BLUE_ON (void);

extern void LED_OFF (void);

extern void RED_ON (void);

extern void Light (void);


#endif
