/*****************************************************************************
* IAR Visual State Coder Generated Source File
* Generated by IAR Visual State 9.1.1.3863
* IAR Visual State Project File: <E:\work_ypl\1_WirelessSwitchboard\3sourcecode\visualSTATE\WorkspaceYPL.vsp>
* IAR Visual State Signature Generator: "81"
* Project Signature: "e89ff9e42730e866831d14f94a50bad8"
*****************************************************************************/


/** @file
    System source file.
    Contains variable and function definitions for a system, including the 
    variable definition of the system class.
*/



/* *** include directives *** */


#include "SystemYPL.h"


/* *** variable definitions *** */


VSActionExprFunctionType const vsactionExpr[3] = 
{
  &RED_ON,  
  &BLUE_ON, 
  &LED_OFF
};

/* System object variables */

VSSystemObject vsso;

/* System class variables */

VSSystemClass const vssc = 
{
  {
    0x000U, 0x001U, 0x003U, 0x005U, 0x006U
  },
  {
    0x001U, 0x004U, 0x010U, 0x008U, 0x00cU, 0x014U
  },
  {
    0x000U, 0x002U, 0x004U, 0x000U, 0x003U, 0x003U, 0x000U, 0x002U, 0x003U, 
    0x003U, 0x001U, 0x001U, 0x003U, 0x002U, 0x001U, 0x001U, 0x003U, 0x001U, 
    0x000U, 0x002U, 0x003U, 0x001U, 0x002U, 0x003U, 0x001U, 0x002U
  },
  {
    0x003U, 0x004U
  },
  {
    0x018U, 0x000U
  },
  {
    0x001U, 0x000U, 0x000U, 0x000U, 0x001U
  }
};

