/*****************************************************************************
* IAR Visual State Coder Generated Header File
* Generated by IAR Visual State 9.1.1.3863
* IAR Visual State Project File: <E:\work_ypl\1_WirelessSwitchboard\3sourcecode\visualSTATE\WorkspaceYPL.vsp>
* IAR Visual State Signature Generator: "81"
* Project Signature: "530ebf83d602e055941637a4b7ff4aa8"
*****************************************************************************/


#ifndef SYSTEMYPL_H
#define SYSTEMYPL_H


/** @file
    System header file.
    Contains macros and declarations for a system.
*/



/* *** include directives *** */


#include "WorkspaceYPL.h"


/* *** type definitions *** */


/* External variable compound types */

typedef struct VSExtVarType_SystemYPL
{
  VS_UCHAR   _x;
}
VSExtVarType_SystemYPL;


/* *** macros *** */


/* External variable macros */
#define x vsextVar_SystemYPL._x


/* *** constants *** */


/* Events */
#define button1 2
#define button2 3
#define button3 4
#define DOOR 5
#define ON 6
#define ROTATION 7
#define STOP 8
#define WASH 9
#define E1 10
#define E2 11
#define E3 12
#define EMERGENCY 13
#define NORMAL 14
#define ON_EW 15
#define ON_NS 16
#define TIMEOUT 17
#define Event2 18
#define Event3 19
#define E_DECREMENT 20
#define E_INCREMENT 21
#define E_MODE 22
/* Constants */
#define val_0 ((VS_UCHAR) 0)
#define MAX ((VS_INT) 10)
#define MIN ((VS_INT) 1)


/* *** variable declarations *** */


/* External variable declarations */

extern VSExtVarType_SystemYPL vsextVar_SystemYPL;


/* Action function declarations */

extern void BLUE_ON (void);

extern void LED_OFF (void);

extern void RED_ON (void);

extern void Light (void);

extern VS_UCHAR AcReturnX (void);


#endif
